spring:
  application:
    name: payment
  mongodb:
    uri: mongodb+srv://Hnin:mongodbhnin@cluster0.qgww1ph.mongodb.net/payment?retryWrites=true&w=majority

server:
  port: 8081

transaction-amount:
  min: 1
  max: 300000

wallet-limit: 10000000

jwt:
  secret: ${JWT_SECRET:asjkdwuet2y56924ihu28u886^&*892rjku2yrj4r%jhgfiefuiwriunc^fuiwhjfnwdwu27489hjIYU^9867HY%}
  expiration-ms: 3600000

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.cache: TRACE
    org.wavemoney.payment: DEBUG